swagger: "2.0"
info: {}
paths: {}
definitions:
  models.User:
    title: User
    type: object
    properties:
      Age:
        type: integer
        format: int64
      Id:
        type: integer
        format: int64
      Name:
        type: string
